[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[fuzz]
runs = 256

[invariant]
runs = 256
depth = 15
fail_on_revert = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
